### ISSUE TITLE
gOmpClause* OmpSupport::buildOmpNonReductionClause(OmpSupport::OmpAttribute*, OmpSupport::omp_construct_enum): Assertion `false' failed.

### ISSUE THREAD

**Issue by chunhualiao** [passlab/rose-develop#1]
Just document make check errors:

./getDataSharingAttribute  -c -rose:openmp:ast_only ../../../../../sourcetree/tests/nonsmoke/functional/CompileTests/OpenMP_tests/parallelfor.c
Warning: buildOmpNoReductionClause(): unhandled clause type: if
lt-getDataSharingAttribute: ../../../../sourcetree/src/frontend/SageIII/ompAstConstruction.cpp:1448: SgOmpClause* OmpSupport::buildOmpNonReductionClause(OmpSupport::OmpAttribute*, OmpSupport::omp_construct_enum): Assertion `false' failed.
make[5]: *** [parallelfor.c.getDataSharingAttribute.output] Aborted (core dumped)
make[5]: Leaving directory `/home/liao6/workspace/yonghong_subcontract/buildtree/tests/nonsmoke/unit/SageInterface'
make[4]: *** [check-am] Error 2
make[4]: Leaving directory `/home/liao6/workspace/yonghong_subcontract/buildtree/tests/nonsmoke/unit/SageInterface'
make[3]: *** [check-recursive] Error 1
make[3]: Leaving directory `/home/liao6/workspace/yonghong_subcontract/buildtree/tests/nonsmoke/unit/SageInterface'
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory `/home/liao6/workspace/yonghong_subcontract/buildtree/tests/nonsmoke/unit'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/liao6/workspace/yonghong_subcontract/buildtree/tests/nonsmoke'
make: *** [check-recursive] Error 1

**Comment by chunhualiao** [comment]
@ouankou Have you tested your work under buildtree/tests/nonsmoke/functional/CompileTests/OpenMP_tests' by typing "make check"?

./parseOmp -rose:openmp:ast_only --edg:no_warnings -w -rose:verbose 0 --edg:restrict  -I../../../../../../sourcetree/src/frontend/SageIII -c ../../../../../../sourcetree/tests/nonsmoke/functional/CompileTests/OpenMP_tests/parallelfor.c 
Warning: buildOmpNoReductionClause(): unhandled clause type: if
lt-parseOmp: ../../../../sourcetree/src/frontend/SageIII/ompAstConstruction.cpp:1448: SgOmpClause* OmpSupport::buildOmpNonReductionClause(OmpSupport::OmpAttribute*, OmpSupport::omp_construct_enum): Assertion `false' failed.
make[3]: *** [rose_parallelfor.c] Aborted (core dumped)
make[3]: Leaving directory `/home/liao6/workspace/yonghong_subcontract/buildtree/tests/nonsmoke/functional/CompileTests/OpenMP_tests'

**Comment by chunhualiao** [comment]
./parseOmp -rose:openmp:ast_only --edg:no_warnings -w -rose:verbose 0 --edg:restrict  -I../../../../../../sourcetree/src/frontend/SageIII -c ../../../../../../sourcetree/tests/nonsmoke/functional/CompileTests/OpenMP_tests/parallelsections.c 
Warning: buildOmpNoReductionClause(): unhandled clause type: if
lt-parseOmp: ../../../../sourcetree/src/frontend/SageIII/ompAstConstruction.cpp:1448: SgOmpClause* OmpSupport::buildOmpNonReductionClause(OmpSupport::OmpAttribute*, OmpSupport::omp_construct_enum): Assertion `false' failed.
make[3]: *** [rose_parallelsections.c] Aborted (core dumped)

**Comment by chunhualiao** [comment]
@yanyh15 @ouankou 
The goal is to pass "make check" within top level build tree. 

It seems like we should make sure "make check" pass under buildtree/tests/nonsmoke/functional/CompileTests/OpenMP_tests  first.

**Comment by chunhualiao** [comment]
I confirm that autoPa has to be updated to use latest reduction creation function of OmpAttribute. @ouankou should provide a documentation (or instructions) about the interface change to OmpAttribute , or an example diff to show how the updates should be done. 

make[3]: Entering directory `/home/liao6/workspace/yonghong_subcontract/buildtree/projects/autoParallelization/tests'
echo "Verifying autoPar translation by using diff ..."; \
if diff rose_accumulateForce.c ../../../../sourcetree/projects/autoParallelization/tests/references/rose_accumulateForce.c > rose_accumulateForce.c.diff ; then echo "Full Option C Test Passed" ; else echo "Files differ; test failed"; cat rose_accumulateForce.c.diff; rm -rf rose_accumulateForce.c.diff; exit 1; fi
Verifying autoPar translation by using diff ...
Files differ; test failed
12c12
< #pragma omp parallel for firstprivate (count)
---
> #pragma omp parallel for reduction (+:sum) firstprivate (count)
make[3]: *** [rose_accumulateForce.c.diff] Error 1

**Comment by ouankou** [comment]
All test cases in ```/tests/nonsmoke/functional/CompileTests/OpenMP_tests```, ```/tests/nonsmoke/functional/roseTests/astInterfaceTests```, and ```/tests/nonsmoke/functional/roseTests/ompLoweringTests``` are passed in the latest WIP branch ```ompparser```.
